AllCops:
  Include:
    - ''
  Exclude:
    - 'unipept.gemspec'
    - 'vendor/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

# disable for now
Lint/NestedMethodDefinition:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
