# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

commands:
  setup:
    description: "Set up repo and dependencies"
    steps:
      - checkout
      - restore_cache:
          keys:
            - unipept-cli-bundle-{{ checksum "Gemfile.lock" }}
            - unipept-cli-bundle-
      - run:
          name: Bundle install
          command: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: unipept-cli-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.3
    working_directory: ~/repo
    steps:
      - setup
      - run:
          name: run tests
          command: bundle exec rake test
  lint:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.3
    working_directory: ~/repo
    steps:
      - setup
      - run:
          name: run tests
          command: bundle exec rake test_style

workflows:
  version: 2
  lint:
    jobs:
      - lint
  test:
    jobs:
      - test
